app/urls.py
from django.conf.urls import url,patterns
from django.views.decorators.csrf import csrf_exempt
from app import views
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = patterns('',

    url(r'^$', RedirectView.as_view(url=reverse_lazy("report_list")) , name="index"),
    url(r'^about/$', views.AboutView.as_view(), name="about"),
    url(r'^upload/$', csrf_exempt(views.UploadFileView.as_view()) , name="fileupload"),
    url(r'^report/(?P<report_id>[0-9]+)/(?P<file_1_id>[0-9]+)/(?P<file_2_id>[0-9]+)/$', views.ComparisonView.as_view(), name="report"),
    url(r'^report/(?P<report_id>[0-9]+)/$', views.ReportView.as_view(), name="report_file_list"),
    url(r'^report/list/$', views.ReportListView.as_view(), name="report_list"),
    url(r'^vulademo$', views.VulaDemoView.as_view(), name="vula_demo"),
    url(r'^api/upload/(?P<user_id>[0-9a-zA-Z]+)/(?P<description>[0-9a-zA-Z]+)/$',  csrf_exempt(views.APIUploadFileView.as_view()), name="apifileupload"),
)

cheaters/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^', include('app.urls')),
    # Examples:
    # url(r'^$', 'djangoTemplate.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

app/models.py
from django.db import models


class Submission(models.Model):
    """
    this model stores the uploaded file contents and its fingerprints along with meta info
    """
    id = models.AutoField(primary_key=True)
    submission_id = models.IntegerField()
    user_id = models.CharField(max_length=20)
    description = models.CharField(max_length=20)
    filename = models.TextField()
    file_contents = models.TextField()
    fingerprint = models.TextField(null=True)
    date = models.DateTimeField('date submitted', auto_now_add=True)


class Report (models.Model):
    """
    this model stores the report for a particular submission
    """
    id = models.AutoField(primary_key=True)
    submission_id = models.IntegerField()
    match_list = models.TextField()
    description = models.CharField(max_length=20)
    date = models.DateTimeField('date submitted', auto_now_add=True)

app/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()
    year = forms.IntegerField(required=False)
    description = forms.CharField(max_length=20)
    param_t = forms.IntegerField(required=False)
    param_n = forms.IntegerField(required=False)
    min_lines_matched = forms.IntegerField(required=False)
    separation_allowance = forms.IntegerField(required=False)
    match_threshold = forms.IntegerField(required=False)


class APIUploadFileForm(forms.Form):
    file = forms.FileField()

app/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse
import operator
from datetime import datetime
from app.submissioncontroller import SubmissionController
from app.models import Report, Submission
from app.forms import UploadFileForm, APIUploadFileForm
from django.views.generic import View
from django.views.generic.edit import FormView
from lib.source_highlighter import highlight


class UploadFileView(FormView):
    """
    This is the view to which batch files are uploaded through a form.
    :return: redirects to report_file_list with the report_id as a parameter
    """

    form_class = UploadFileForm

    def form_valid(self, form):
        # if form contains no validation errors then process form
        # delete the file and description keys from the dictionary after
        # getting them to easily get the remaining parameters
        file = form.cleaned_data["file"]
        del form.cleaned_data["file"]
        description = form.cleaned_data["description"]
        del form.cleaned_data["description"]

        parameters = {}

        # get the optional parameters which have been specified
        for key, value in form.cleaned_data.items():
            if value is not None:
                parameters[key] = value

        sub_controller = SubmissionController(file, description, **parameters)

        report = sub_controller.report
        response = {"report_id": report.id}
        response = json.dumps(response)

        return HttpResponse(response, content_type="application/json")

    def form_invalid(self, form):
        # send back validation errors
        data = json.dumps(form.errors)
        print(data)
        return HttpResponse(data, status=400, content_type='application/json')


class APIUploadFileView(FormView):
    """
    View for API for third party applications to submit single user files to this system.
    :return: returns a percent match in a json object
    """

    def post(self, request, user_id, description):

        form_class = APIUploadFileForm
        form = self.get_form(form_class)

        if form.is_valid():
            file = form.cleaned_data["file"]
            kwargs = {"year": 2000}
            sub_controller = SubmissionController(file, user_id, description, admin_submission=False, **kwargs)
            report = sub_controller.report

            report.match_list.sort(key=operator.itemgetter("percent_match"), reverse=True)
            percent_match = report.match_list[0].get("percent_match") if report.match_list else 0
            response = {"percent_match": percent_match}
            response = json.dumps(response)
            return HttpResponse(response, content_type="application/json")

        else:
            data = json.dumps(form.errors)
            return HttpResponse(data, status=400, content_type='application/json')


class AboutView(View):
    """
    gives a list of the comparisons in the report
    """
    def get(self, request):
        return render(request, "about.html")


class ReportView(View):
    """
    gives a list of the comparisons in the report
    """
    def get(self, request, report_id):
        report = Report.objects.get(id=report_id)
        report.match_list = eval(report.match_list)
        report.match_list.sort(key=operator.itemgetter("percent_match"), reverse=True)
        # get the corresponding user_id and filename for each file id and insert it into the dictionary
        for match in report.match_list:
            submission = Submission.objects.get(id=match["file_2"])
            match["user2"] = submission.user_id
            submission = Submission.objects.get(id=match["file_1"])
            match["user1"] = submission.user_id

        return render(request, "report.html", {"title": "Report File List",
                                                        "report_id": report_id,
                                                        "object_list": report.match_list})


class ComparisonView(View):
    """
    shows the comparison between 2 given files.
    """
    def get(self, request, report_id, file_1_id, file_2_id):
        report = Report.objects.get(id=report_id)
        report.match_list = eval(report.match_list)
        file_1_id = int(file_1_id)
        file_2_id = int(file_2_id)
        #need to find the particular comparison comparing the 2 files with file_1_id and file_2_id
        comparison = [x for x in report.match_list if x["file_1"] == file_1_id and x["file_2"] == file_2_id][0]

        line_matches = comparison["line_matches"]
        # get the two sources files from the database
        file1 = Submission.objects.get(id=file_1_id)
        file2 = Submission.objects.get(id=file_2_id)
        # highlight the necessary lines
        source1 = highlight(file1.file_contents, line_matches, 0)
        source2 = highlight(file2.file_contents, line_matches, 1)

        return render(
            request,
            "comparison.html",
            {
                "title": "Report Page",
                "year": datetime.now().year,
                "percent_match": comparison["percent_match"],
                "file1": source1,
                "file2": source2
            })


class ReportListView(View):
    """
    lists the reports for submissions flagged
    """
    def get(self, request):
        report_list = Report.objects.all().order_by("-date")

        return render(
            request,
            "report_list.html",
            {
                "title": "Report List Page",
                "year": datetime.now().year,
                "report_list": report_list,
            })


class VulaDemoView(View):
    """
    Provides a simple button to use the API
    """
    def get(self, request):
        return render(request, "vula_demo.html")

app/templates/about.html
{% extends "layout.html" %}
{% block content %}

    <div class="heading">Format for submission file</div>
    Submissions need to be uploaded as a zip file. The root of this zip file should contain folders named as users. Each folder should contain the source files belonging to that specific user.
    An example is shown below. </br></br>
    <div class="zip-example">
        Assignment1.zip </br>
        &mdash; John/ </br>
        &mdash;&mdash; Question1.py </br>
        &mdash;&mdash; Question2.py </br>
        &mdash; Mary/ </br>
        &mdash;&mdash; Question1.py </br>
        &mdash;&mdash; Question2.py </br>
    </div>


    </br></br>

    <div class="text-left heading">Parameters</div>

    <table class="table table-striped box-glow">
        <thead>
            <tr>
                <th>Parameter</th>
                <th>Default</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><b>Description</b></td>
                <td>Compulsory field</td>
                <td>
                    Something which will help you identify this submission at a later stage. This is the only required field.
                </td>
            </tr>
            <tr>
                <td><b>Compare from year</b></td>
                <td>None</td>
                <td>
                    If you are comparing to past submissions, only submissions which were submitted on this year or later will be considered. Leaving this blank means no history comparisons will be made.
                </td>
            </tr>
            <tr>
                <td><b>t</b></td>
                <td>10</td>
                <td>
                    If there is a substring match <i>at least</i> as long as <b>t</b>, then this match is guaranteed to be detected. Keep in mind that function and variable names will be replaced and counted as one character.
                </td>
            </tr>
            <tr>
                <td><b>n</b></td>
                <td>6</td>
                <td>
                    No matches shorter than the <b>n</b> will be detected.
                </td>
            </tr>
            <tr>
                <td><b>Min lines matched</b></td>
                <td>3</td>
                <td>
                    The minimum number of consecutive lines which need to match before the set is flagged.
                </td>
            </tr>
            <tr>
                <td><b>Separation allowance</b></td>
                <td>2</td>
                <td>
                    Sometimes there will be large matching blocks of code. If there is one line in the middle of the block somewhere, it will split the block in two. This parameter controls how many lines within a block are allowed to <i>not</i> match, without splitting the larger block.
                </td>
            </tr>
            <tr>
                <td><b>Match threshold</b></td>
                <td>10</td>
                <td>
                    This is a percentage. All matches smaller than this will be discarded.
                </td>
            </tr>
        </tbody>
    </table>
    </br></br>

    <div class="heading">Authors</div>
    <p>
        This cheating detection system was written by Brendan Ball, Darren Silke and Andrew van Rooyen as a 3rd year Computer Science project at the University of Cape Town
    </p>


{% endblock %}

app/templates/comparison.html
{% extends "layout.html" %}

{% block content %}
<div>


	<div class="text-center heading">{{ percent_match }}% similarity</div>
	{% autoescape off %}
    <div class="comparison-wrapper">
        <div class="filebox box-glow float-left"> {{ file1 }} </div>
        <div class="filebox box-glow float-right"> {{ file2 }} </div>
    </div>
	{% endautoescape %}



</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
{# Theme is at http://bootswatch.com/slate/ #}
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}" />
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.min.js"></script>
    <script src="{% static 'js/site.js' %}"></script>
</head>

<body>
	<div class="navbar navbar-default">
		<div class="navbar-collapse collapse navbar-responsive-collapse">
			<ul class="nav navbar-nav">
				<li class="emph" id="home"><a href="{% url 'report_list' %}">Home</a></li>
                <li class="emph" id="about"><a href="{% url 'about' %}">About</a></li>
                <li class="emph" id="about"><a href="{% url 'vula_demo' %}">Vula Demo</a></li>
			</ul>
		</div>
	</div>


	<div class="container body-content">
		{% block content %}
		{% endblock %}
	</div>


</body>
</html>

app/templates/report.html
{% extends "layout.html" %}

{% block content %}
<div class="heading text-center">Comparisons for report {{ report_id }}</div>
<div class="file-list-container box-glow">

	<table class="table table-striped table-hover table-links-block">
		<thead>
			<tr>
				<th>#</th>
				<th>Match %</th>
				<th>User A</th>
				<th>User B</th>
			</tr>
		</thead>
		<tbody>
			{% for comparison in object_list %}
			<tr>
				<td>
					<a href="{% url 'report' report_id comparison.file_1 comparison.file_2 %}">
						{{ forloop.counter }}
					</a>
				</td>
                <td>
					<a href="{% url 'report' report_id comparison.file_1 comparison.file_2 %}">
						{{ comparison.percent_match }}
					</a>
				</td>
				<td>
					<a href="{% url 'report' report_id comparison.file_1 comparison.file_2 %}">
						{{ comparison.user1 }}
					</a>
				</td>
				<td>
					<a href="{% url 'report' report_id comparison.file_1 comparison.file_2 %}">
						{{ comparison.user2 }}
					</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

</div>

{% endblock %}

app/templates/report_list.html
{% extends "layout.html" %}


{% block content %}

<table>
    <tbody>
        <tr>
            <td>
                <div class="upload-form-container">
                <div class="heading">New Submission</div>
                {% block uploadfile %}
                    {% include "upload_file_form.html" %}
                {% endblock %}
                </div>
            </td>

            <td>
                <div class="text-center heading">List of Reports{{ report_id }}</div>
                <div class="file-list-container box-glow">

                    <table class="table table-striped table-hover table-links-block">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Date</th>
                                <th>Description</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for report in report_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'report_file_list' report.id %}">
                                        {{ report.id }}
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'report_file_list' report.id %}">
                                        {{ report.date }}
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'report_file_list' report.id %}">
                                        {{ report.description }}
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

app/templates/upload_file_form.html
<div>
    <form class="form-horizontal" id="uploadform" action="{% url "fileupload" %}" method="post" enctype="multipart/form-data" >
        <div class="form-group" id="error_messages">
        </div>
        <div class="form-group">
            <input class="file-input-hidden" id="id_file" name="file" type="file"/>
            <span class="col-xs-2">
                <input class="btn btn-primary upload-form col-xs-2" id="id_fake_file_button" type="button" value="Select zip file" />
                <div class="text-center" for="id_file" id="id_file_name"></div>
            </span>
        </div>
        <div class="form-group">
            <span class="col-xs-2">
                <input class="input-sm" id="id_description" name="description" type="text" placeholder="*Description" />
            </span>
        </div>
        <div class="form-group">
            <span class="col-xs-2">
                <input class="input-sm" id="id_year" name="year" type="text" placeholder="Compare from year" />
            </span>
        </div>
        <div class="form-group">
            <span class="col-xs-2">
                <input class="input-sm" id="id_param_t" name="param_t" type="text" placeholder="t"/>
            </span>
        </div>
        <div class="form-group">
            <span class="col-xs-2">
                <input class="input-sm" id="id_param_n" name="param_n" type="text" placeholder="n"/>
            </span>
        </div>
        <div class="form-group">
            <span class="col-xs-2">
                <input class="input-sm" id="id_min_lines_matched" name="min_lines_matched" type="text" placeholder="Min lines matched" />
            </span>
        </div>
        <div class="form-group">
            <span class="col-xs-2">
                <input class="input-sm" id="id_separation_allowance" name="separation_allowance" type="text" placeholder="Separation allowance" />
            </span>
        </div>
        <div class="form-group">
            <span class="col-xs-2">
                <input class="input-sm" id="id_match_threshold" name="match_threshold" type="text" placeholder="Match threshold" />
            </span>
        </div>
        <div class="form-group">
            <span class="col-xs-2">
                <input class="btn btn-primary" type="submit" value="Submit"/>
            </span>
        </div>
    </form>
</div>

app/templates/vula_demo.html
{% extends "layout.html" %}


{% block content %}

This zip file should be named as a student number and contain no folders

<div>
    <form class="form-horizontal" id="apiform" action="/api/upload/john/description/" method="post" enctype="multipart/form-data" >

        <div class="form-group">
            <input class="file-input-hidden" id="id_file" name="file" type="file"/>
            <span class="col-xs-2">
                <input class="btn btn-primary upload-form col-xs-2" id="id_fake_file_button" type="button" value="Select zip file" />
                <div class="text-center" for="id_file" id="id_file_name"></div>
            </span>
        </div>

        <div class="form-group">
            <span class="col-xs-2">
                <input class="btn btn-primary" type="submit" value="Submit"/>
            </span>
        </div>

    </form>
</div>

{% endblock %}